version: 2
jobs:
  build:
    working_directory: ~/technobabble
    docker:
      - image: openjdk:8
      - image: circleci/clojure:lein-2.7.1
      - image: postgres:9.4.1
        # The official Postgres docker images will create your DB for you
        # if you set the POSTGRES_DB environment variable.
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: technobabble
    environment:
      DATABASE_URL=postgres://localhost/technobabble
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      # Pull the dependencies in a way that they're cached.
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: lein deps
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: << checksum "project.clj" >>
      # Linting
      - run: lein eastwood "{:namespaces [:source-paths]}"
      # Formatting
      - run: lein cljfmt fix
      # Migrate the DB, then test.
      # - run: lein test
      # Push it out to Heroku on a successful master build.
      # - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master