version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
      - image: circleci/postgres:9.4
      # environment:
      #     POSTGRES_USER: root
      #     POSTGRES_DB: technobabble
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
      # DATABASE_URL=postgres://localhost/technobabble
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      # Formatting
      - run: lein cljfmt fix
      # Linting
      - run: lein eastwood
      # run tests
      # - run: lein test